"""empty message

Revision ID: d284c0de2252
Revises: 
Create Date: 2023-04-11 20:29:33.597602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd284c0de2252'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_scholar_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_info', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_scholar_profiles', schema=None) as batch_op:
        batch_op.drop_column('about_info')

    # ### end Alembic commands ###
